//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromosiMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PromosiDBModelContainer : DbContext
    {
        public PromosiDBModelContainer()
            : base("name=PromosiDBModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Company> CompanySet { get; set; }
        public virtual DbSet<Branch> BranchSet { get; set; }
        public virtual DbSet<City> CitySet { get; set; }
        public virtual DbSet<Push> PushSet { get; set; }
        public virtual DbSet<Pushes> PushesSet { get; set; }
        public virtual DbSet<Log> LogSet { get; set; }
        public virtual DbSet<LogType> LogTypeSet { get; set; }
        public virtual DbSet<Followings> FollowingsSet { get; set; }
    }
}
